import { faker } from '@faker-js/faker';

export interface User {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  phone: string;
  role: 'admin' | 'customer' | 'viewer';
}

export const UserFactory = {
  /**
   * Build one User. Pass overrides to pin specific fields; the rest are
   * generated by Faker so every call produces a valid, unique record.
   */
  create(overrides: Partial<User> = {}): User {
    return {
      email: faker.internet.email().toLowerCase(),
      // prefix 'Aa1!' satisfies typical "must contain upper/lower/digit/special" rules
      password: faker.internet.password({ length: 12, prefix: 'Aa1!' }),
      firstName: faker.person.firstName(),
      lastName: faker.person.lastName(),
      phone: faker.phone.number(),
      role: 'customer',
      ...overrides,
    };
  },

  /**
   * Build one User with Vietnamese-style phone (+84) and common VN names.
   * Useful for locale-specific edge-case tests.
   */
  createVietnamese(overrides: Partial<User> = {}): User {
    return this.create({
      firstName: faker.helpers.arrayElement(['Nguyễn', 'Trần', 'Lê', 'Phạm', 'Hoàng']),
      lastName: faker.helpers.arrayElement([
        'Văn An',
        'Thị Bình',
        'Đức Minh',
        'Thanh Hương',
        'Quốc Khánh',
      ]),
      phone: `+84${faker.string.numeric(9)}`,
      ...overrides,
    });
  },

  /**
   * Build N users. Returns [] for n ≤ 0 — callers should guard upstream if
   * they expect at least one record, but this never throws.
   */
  createMany(n: number, overrides?: Partial<User>): User[] {
    if (n <= 0) return [];
    return Array.from({ length: n }, () => this.create(overrides));
  },
};
